[[media]]
id = "sparky"
media_type = "image"
url = "media/jpg/car_drawing.jpg"
title = "2020 FSAE Car"
section = "fsae"
description = """
A drawing of the Lafayette FSAE car. Named \"Sparky\" for many sparks we
produced while making it. The main battery packs are mounted to either side of
the cockpit."
"""


# Battery Packs

# [[media]]
# id = "pack-drawing"
# media_type = "image"
# title = "Pack Exterior"
# url = "media/bms/pack_drawing.PNG"
# section = "fsae"
# description = "An exterior drawing of a battery pack. "


[[media]]
id = "pack-assembly"
media_type = "image"
title = "Construction"
url = "media/jpg/pack_inside.jpg"
section = "fsae"
description = """
<p>
Each battery is built of 16 Prismatic, Lithium Iron Phosphate Cells connected 
in series. The cells are divided into two segments of 8 cells each, which are
isolated from eathother by a garolite wall. Segments are connected together by
a large switch, called a Segment Maintenance Disconnect or SMD, which can be
opened to completely disable the pack and prep it for safer maintenance.
</p>
<p>
A third compartment at the front of the pack is used to mount all electronics
that are not a part of either segment, including the Pack Management (PacMan)
board, the Pack Display Panel, fuses, and isolation relays. Additional garolite
walls separate this compartment from the two segments, as well as high and low
voltage sections of the pack circuitry itself.
</p>
"""

[[media]]
id = "pack-interfaces"
media_type = "image"
title = "Pack Interfaces"
url = "media/svg/pack_drawing_connectors.svg"
section = "fsae"
description = "An exterior drawing of a battery pack. Each pack has a side mounted display panel for fault reporting, configuration, and charging, a Segment Maintenance Disconnect (SMD) switch, which breaks the connection between segments, and a panel of connectors that connect the pack to the car's other subsystems. <p>In addition to the display panel, each pack connects to the car's CAN bus, and is fully compliant with the CANOpen standard. This interface is used primarily for broadcasting information about the pack to the car's other subsystems, but can also be used to reconfigure pack behavior and control it at a high level. </p>"

[[media]]
id = "segment-diagram"
media_type = "image"
title = "Active Balancing"
url = "media/svg/segment_diagram.svg"
description = "Each segment is also equipped with an experimental active balancing circuit for redistributing power between cells during charging and discharging. In this design, each cell has a dedicated Flyback Converter which steps the nominal cell voltage up to that of the full segment, and feeds that into a dedicated \"Balance Bus\" that connects the output of each converter together in parallel. Jumpers on the highest and lowest cell in the segment allow current from the balance bus to flow back into the segment where it charges the other cells."
# description = "This high level diagram shows how the active balancing circuit integrated into each Segment is intended to function. Flyback Converters on each CellMan board step up a Cell's Voltage to that of the full segment, and power is fed back into the segment through jumpers on the highest and lowest CellMen in the stack."
section = "fsae"

[[media]]
id = "cellman-interfaces"
media_type = "image"
title = "PacMan"
url = "media/png/pac_man_render.png"
section = "fsae"
description = "A render of the Pack Management Board, which is responsible for high level control of the BMS, power distribution, interfacing with the car's other subsystems, and making additional measurements not associated with a specific cell, such as output current and ambient pack temperature."
