[[gallery]]
id = "sparky"
title = "2020 FSAE Car"
image = "media/fsae/car_drawing.jpg"

[[gallery]]
id = "pack-drawing"
title = "Battery Pack Drawing"
image = "media/bms/pack_drawing.PNG"

[[gallery]]
id = "pack-interfaces"
title = "External Connectors and Interfaces"
image = "media/bms/pack_drawing_connectors.svg"

[[gallery]]
id = "pack-assembly"
title = "Inside of Partially Assembled Battery Pack"
image = "media/bms/pack_inside.jpg"

[[gallery]]
id = "segment-diagram"
title = "Segment Power Distribution and Active Balancing"
image = "media/bms/segment_diagram.svg"

[[gallery]]
id = "cellman-render"
title = "CellMan Version 2.2 Render"
image = "media/bms/cell_man_render.png"

[[gallery]]
id = "cellman-drawing"
title = "CellMan Connectors and Interfaces"
image = "media/bms/cell_man_drawing.svg"
